# Generated by Django 4.2.18 on 2025-01-21 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_delete_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase',
            old_name='user',
            new_name='buyer',
        ),
    ]
