# Generated by Django 4.2.18 on 2025-01-31 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_alter_review_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(choices=[(1, '★☆☆☆☆ (1)'), (2, '★★☆☆☆ (2)'), (3, '★★★☆☆ (3)'), (4, '★★★★☆ (4)'), (5, '★★★★★ (5)')]),
        ),
    ]
